#!/usr/bin/env bash

sudo apt-get -y update

# dowload required packages for docker
sudo apt-get -y install ca-certificates curl gnupg lsb-release

# create directory keyrings
mkdir -p /etc/apt/keyrings

#get docker repository
[ ! -f /etc/apt/keyrings/docker.gpg ] && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg || echo "Already docker image"

#set docker repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# set a version to get a common version
VERSION_STRING=5:20.10.13~3-0~ubuntu-jammy

# set a loop variable
loop=0

snap install docker
#sudo apt-get -y install docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-compose-plugin

#installation result
if [[ docker ]]
then
        echo "Docker installation successed"
else
        echo "Docker installation failed"
fi

